### ISSUE TITLE
Top-level Module Named Hashring conflicts with other libraries

### ISSUE THREAD

**Issue by geofflane** [discordapp/ex_hash_ring#3]
https://github.com/bitwalker/libring has the exact same module name

**Comment by gmjosack** [comment]
Hey @geofflane, Thanks for the heads up and sorry about that! I'll look into getting this fixed up.

**Comment by geofflane** [comment]
:+1:

**Comment by gmjosack** [comment]
As a final follow up a new release of redlock went out that uses the new version of ex_hash_ring so that should avoid the conflict.

https://hex.pm/packages/redlock/1.0.3

**Comment by geofflane** [comment]
:heart: Thanks so much for the speed fixes and the followups!
